### ISSUE TITLE
Impulse based collision resolution

### ISSUE THREAD

**Issue by benthacher** [benthacher/pal-engine#3]
# Goal
Implement impulse based collision resolution between any two phys_data. This consists of checking for collisions, emitting events on involved entities, adding collision manifold resolving if entities want that (add config flag for collisions). Honestly not sure where "collision manifold" comes from, I just used it in a previous game engine and might change the name to something like collision descriptor or something.

# Tasks
- [x] Implement some kind of collision detection (SAT probably)
- [x] Add collision entity_event. What do I pass to the event handler?
- [x] Add do_collisions config flag
- [x] Add collision information as collision descriptor to dynamic list of descriptors to be resolved later
- [x] Resolve collisions in the physics portion of the game loop
